DROP TABLE assay CASCADE CONSTRAINTS
;
DROP TABLE assay_cvparam CASCADE CONSTRAINTS
;
DROP TABLE assay_ptm CASCADE CONSTRAINTS
;
DROP TABLE assay_userparam CASCADE CONSTRAINTS
;
DROP TABLE authorities CASCADE CONSTRAINTS
;
DROP TABLE contact CASCADE CONSTRAINTS
;
DROP TABLE cv_param CASCADE CONSTRAINTS
;
DROP TABLE instrument CASCADE CONSTRAINTS
;
DROP TABLE instrument_component CASCADE CONSTRAINTS
;
DROP TABLE instrument_component_cvparam CASCADE CONSTRAINTS
;
DROP TABLE instrument_component_userparam CASCADE CONSTRAINTS
;
DROP TABLE project CASCADE CONSTRAINTS
;
DROP TABLE project_cvparam CASCADE CONSTRAINTS
;
DROP TABLE project_files CASCADE CONSTRAINTS
;
DROP TABLE project_ptm CASCADE CONSTRAINTS
;
DROP TABLE project_userparam CASCADE CONSTRAINTS
;
DROP TABLE project_users CASCADE CONSTRAINTS
;
DROP TABLE reference CASCADE CONSTRAINTS
;
DROP TABLE software CASCADE CONSTRAINTS
;
DROP TABLE software_cvparam CASCADE CONSTRAINTS
;
DROP TABLE software_userparam CASCADE CONSTRAINTS
;
DROP TABLE pride_users CASCADE CONSTRAINTS
;
DROP TABLE lab_head CASCADE CONSTRAINTS
;
DROP TABLE project_tag CASCADE CONSTRAINTS
;
DROP SEQUENCE assayParamSequence
;
DROP SEQUENCE assayPtmSequence
;
DROP SEQUENCE assaySequence
;
DROP SEQUENCE authoritySequence
;
DROP SEQUENCE contactSequence
;
DROP SEQUENCE instrCompParamSequence
;
DROP SEQUENCE instrCompSequence
;
DROP SEQUENCE instrumentSequence
;
DROP SEQUENCE paramSequence
;
DROP SEQUENCE projectFileSequence
;
DROP SEQUENCE projectParamSequence
;
DROP SEQUENCE projectPtmSequence
;
DROP SEQUENCE projectSequence
;
DROP SEQUENCE referenceSequence
;
DROP SEQUENCE softwareParamSequence
;
DROP SEQUENCE softwareSequence
;
DROP SEQUENCE prideUserSequence
;
DROP SEQUENCE labHeadSequence
;
DROP SEQUENCE projectTagSequence
;
